### ISSUE TITLE
Matching across multiple fields

### ISSUE THREAD

**Issue by hmnd** [maxharlow/csvmatch#18]
Hello,
It appears as though you don't combine the degrees of multiple fields and instead look at them individually. I'm looking to combine the degree from matching name and address. Any idea on how to accomplish that?

**Comment by hmnd** [comment]
Also, just to clarify: this is for fuzzy matching.

**Comment by maxharlow** [comment]
Hi there. Which fuzzy matching method have you been using?

**Comment by hmnd** [comment]
#19 would fix

**Comment by maxharlow** [comment]
Fixed in v1.18
