### ISSUE TITLE
descriptor 'union' of 'set' object needs an argument

### ISSUE THREAD

**Issue by r3ptar** [maxharlow/csvmatch#21]
I am receiving "descriptor 'union' of 'set' object needs an argument" when using --fuzzy. This is happening after I hit f to finish matching records for the machine learning. Below is my syntax:

csvmatch file1.csv file2.csv --fields1 'Employee#' 'Last Name' First Name' --fields2 'Employee#' 'Last Name' 'First Name' --fuzzy > newfile.csv

**Comment by maxharlow** [comment]
Which version are you using? Find out with `csvmatch -v`.

Could you also try running it with `--fuzzy levenshtein` and see if you get the same error?

**Comment by r3ptar** [comment]
Version is 1.17

Running with levenshtein seemed to have worked just fine, but the results are incredibly wrong.. Is this limited to only comparing between two documents? or could I do 3 or 4?

**Comment by maxharlow** [comment]
It seems it's a problem with the default machine-learning Bilenko method of fuzzy matching. If you need a workaround for now you could try either adjusting the Levenshtein match threshold using `-r`, or using the other fuzzy matching methods.

Could you try upgrading to 1.18 and see if you still get the same error?

CSV Match can only match between two spreadsheets -- if you needed to match between more than that you could use the output from matching files one and two against the third file, and so on for further files.

**Comment by r3ptar** [comment]
How can I upgrade to 1.18? When I pull I get 1.17

**Comment by r3ptar** [comment]
Upgraded to 1.18. Now it doesn't do anything just display > in terminal.

**Comment by maxharlow** [comment]
Oh. Is that just with the default fuzzy matching, or with anything? Are you on Mac or Windows? Which version of Python?

**Comment by r3ptar** [comment]
yeah that's just with default fuzzy. Normal matches work just fine. I'm running this on centos 7 using Python 2.7.5

**Comment by maxharlow** [comment]
Ok -- does it give that error for any files you try and match, or just a specific one?

**Comment by r3ptar** [comment]
any files

**Comment by maxharlow** [comment]
Hmm.. I'm not sure how I can reproduce this. Perhaps try with it installed with Python 3?

**Comment by r3ptar** [comment]
I just downgraded my csv version and then reinstalled python and it seems to have resolved things for me. I was able to successfully run my match.

**Comment by maxharlow** [comment]
Excellent! :+1:
