### ISSUE TITLE
-l option example or documentation

### ISSUE THREAD

**Issue by aborruso** [maxharlow/csvmatch#27]
Hi,
for `-l` I read "filter out terms from a newline-separated file of regular expressions when comparing".

But how to use it? Could you add an example with two lines of regular expressions to apply to the compare job?

Thank you

**Comment by maxharlow** [comment]
Based on your other issues I'm assuming you figured it out. It's just a text file with a regex on each line. You can see [a built-in example used in the `-t` option](https://github.com/maxharlow/csvmatch/blob/master/csvmatch-titles.txt.py). (Ignore the `.py` extension in the filename, that's packaging thing.)

It could do with an example in the readme, agreed.

**Comment by aborruso** [comment]
@maxharlow thank you.

Then if I write in the `-l` file

```
^000.+
```

and apply it to

```
Number
0005325
0253156
ZZZ0003653
```

I will have in output the strings below?

```
Number

0253156
ZZZ0003653
```

Are these regex to remove characters? Am I right?

**Comment by maxharlow** [comment]
The removal only takes place internally during the matching between the two files -- in the output the data will be the same as it is in the input. And yes, it's to remove -- anything that matches is removed

**Comment by aborruso** [comment]
@maxharlow look here http://youtu.be/cUfAunJnUuU?hd=1

My files are

```
# rule.txt
 $
```

```
# input_01.csv
Name,Age
Andy,32
Mary-Jane,43
Andrè,50
```

```
#input_02.csv
Name,City
Andy,Rome
Mary Jane,New York
Andre',Palermo
```

**Comment by aborruso** [comment]
Ops,  I have replied to the wrong thread, sorry
