### ISSUE TITLE
Functionality to upload known matches during training of fuzzy match? 

### ISSUE THREAD

**Issue by sskadamb** [maxharlow/csvmatch#30]
In Dedupe's library we see the option to [prepare_training](https://docs.dedupe.io/en/latest/API-documentation.html#Dedupe.prepare_training) and start off with some known matches for training data. However, is this functionality available in `csvmatch` to pass in another training file also?

**Comment by maxharlow** [comment]
Afraid there isn't an option for that yet. You're better off using the `csvlink` tool that comes with https://github.com/dedupeio/csvdedupe which lets you do that.

**Comment by maxharlow** [comment]
Closing this in favour of https://github.com/maxharlow/csvmatch/issues/2
