### ISSUE TITLE
Fuzzy merge for integer values 

### ISSUE THREAD

**Issue by andreys42** [maxharlow/csvmatch#31]
Am I wrong , fuzzy_pandas cant handle fuzzy logic related to integer values? Let's say we have fuzzy coordinates (X,Y). The only way is to convert them to string?
Thank you

**Comment by maxharlow** [comment]
This is CSV Match, which fuzzy_pandas wraps. You're correct, only strings are handled. You probably want to use another library or implement your own handling of numerical similarity.
