### ISSUE TITLE
invalid value encountered in double_scalars module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by seifeur** [maxharlow/csvmatch#32]
Hello, in python 3.8 on windows, when you run the Bilenko match and after you enter the response y/n you have the next error :
invalid value encountered in double_scalars
module 'time' has no attribute 'clock'

**Comment by maxharlow** [comment]
Hi there. I think this may be a Python 3.8 issue. I think this should be fixed with v1.20, if you could check?
