### ISSUE TITLE
bug: wrong number of carriage return in output

### ISSUE THREAD

**Issue by aborruso** [maxharlow/csvmatch#33]
Hi,
I have these two example CSVs

```
cat input_01.csv

field1,field2
a,b
c,d
```

```
cat input_02.csv

field1,field3
a,12
c,13
```

If I run 

```
csvmatch input_01.csv input_02.csv --fields1 "field1" --fields2 "field1" --output 1.field1 2.field3 >out.csv
```

I have two (and not only one) carriage return in the output file, and this is an error because row 4 is completely blank.

```
field1,field3
a,12
c,13


```

Thank always you for this great tool

**Comment by maxharlow** [comment]
Thanks for the bug report! This is fixed in https://github.com/maxharlow/csvmatch/commit/c043831bc1a4ddf8af12afd86774df3a83f17d56, and will be incorporated into the next release

**Comment by aborruso** [comment]
@maxharlow as usual thank you very much for all!
