### ISSUE TITLE
Ignore_letters option

### ISSUE THREAD

**Issue by hjohns12** [maxharlow/csvmatch#34]
For the purpose of matching strings with helpful numbers and unhelpful words (such as precinct names with codes and messy names), adding an "ignore_letters" option would be nice. This would only match numbers from two columns of interest.

I implemented something like this in my code with:

```
def ignore_alpha(row):
    regex = re.compile('[\D_]+')
    return [regex.sub('', value) for value in row]
```

**Comment by maxharlow** [comment]
This can be achieved with the Regex ignore function
