### ISSUE TITLE
Issues with dedupe dependency because of Levenshtein-search

### ISSUE THREAD

**Issue by stefan-grafberger** [maxharlow/csvmatch#38]
Hi,

Thank you for your project!

I use csvmatch for a project but started getting build issues since today or a few days ago. It seems like Levenshtein-search==1.4.5, which dedupe depends on, is no longer available on pip. Others created issues in their repository, but there has been no solution so far: https://github.com/mattandahalfew/Levenshtein_search/issues/29

The dedupe package released a hotfix to no longer depend on Levenshtein-search==1.4.5, but to use that hotfix the dedupe dependency in csvmatch would need to be updated from 2.0.11 to 2.0.21. Would it be possible to update this dependency and create a new release?

**Comment by maxharlow** [comment]
Hi there! This should be fixed as of v1.23

**Comment by stefan-grafberger** [comment]
Great, that was quick! Thank you!
