### ISSUE TITLE
Installation on Mac -- scikit-learn Issue

### ISSUE THREAD

**Issue by markroyko** [maxharlow/csvmatch#39]
During the install process on my Mac, I seem to be getting an error when it comes to scikit-learn.  Any advice?
`Collecting scikit-learn (from dedupe==2.0.21->csvmatch)
  Using cached scikit-learn-1.2.2.tar.gz (7.3 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
      Collecting setuptools
        Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting Cython>=0.29.24
        Using cached Cython-0.29.34-py2.py3-none-any.whl (988 kB)
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
      Collecting scipy>=1.3.2
        Using cached scipy-1.10.1.tar.gz (42.4 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
`

**Comment by maxharlow** [comment]
A new major version has just been released, please see if that resolves your issue
