### ISSUE TITLE
Parameter to include original line numbers in output

### ISSUE THREAD

**Issue by maxharlow** [maxharlow/csvmatch#5]

**Comment by lsdh** [comment]
I would like to see support for matching _line numbers_ if this is possible. That way you could tell which rows match on which csv.

I also  wanted to say thank you for this useful program, saves having to run time consuming formula's in Excel to find a match! :+1:

**Comment by maxharlow** [comment]
@lsdh thanks! Glad you've found it useful. To clarify -- by matching line numbers do you mean so that ordering matters?

**Comment by lsdh** [comment]
For example -

List 1:
1. apples
2. oranges
3. apricots

List 2:
1. apricots
2. oranges
3. apples

Output:
line 1 : apples, line 3: apples
line 2: oranges, line 2 : oranges
line 3: apricots, line 1: apricots

It would help identify which row contains the duplicate/matching number in each list.
If this is not possible no worries, it's still a great little python program.
